---
id: rubykaigi2014
base_name: ruby-removed-features
tags:
- ruby
presentation_date: 2014.9.19
version: 0.0.3
licenses: []
slideshare_id: rubykaigi2014
speaker_deck_id: archaeology-of-ruby-removed-features-ruby
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :rd
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
